2014/fakefarm/silo/minitest/reference/minishop/config/routes.rb
Rails.application.routes.draw do
  root to: "store#index"

  resources :products
  resources :carts, only: [ :destroy ]
  resources :line_items, only: [ :create ]
  resources :orders, only: [ :index, :show, :new, :create ]
  resources :users

  controller :sessions do
    get "login", action: "new"
    post "login", action: "create"
    delete "logout", action: "destroy"
  end
end

2014/fakefarm/silo/minitest/reference/minishop/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
	      data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
            <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MiniShop</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
	<%= admin_navbar_item "Products", products_path, controller_path =~ /products/ %>
	<%= admin_navbar_item "Users", users_path, controller_path =~ /users/ %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
	<%= login_navbar_item %>
      </ul>
    </div>
  </div>
</nav>

2014/fakefarm/silo/minitest/reference/minishop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MiniShop</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body id="store">
    <%= render partial: "layouts/navigation" %>

    <div id="main" class="container">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </body>
</html>

2014/fakefarm/silo/minitest/reference/minishop/app/views/layouts/store.html.erb
<% content_for :content do %>
  <div class="sidebar">
    <div id="cart">
      <%= render @cart %>
    </div>
  </div>

  <div class="entries">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>