2014/fakefarm/silo/minitest/reference/minishop/config/routes.rb
Rails.application.routes.draw do
  root to: "store#index"

  resources :products
  resources :carts, only: [ :destroy ]
  resources :line_items, only: [ :create ]
  resources :orders, only: [ :index, :show, :new, :create ]
  resources :users

  controller :sessions do
    get "login", action: "new"
    post "login", action: "create"
    delete "logout", action: "destroy"
  end
end

2014/fakefarm/silo/minitest/reference/minishop/app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = ["Check" , "Credit Card" , "Purchase Order"]

  has_many       :line_items, dependent: :destroy

  validates      :name, :address, :email, :pay_type, presence: true
  validates      :pay_type, inclusion: PAYMENT_TYPES

  after_commit   ConfirmationEmailSender.new, on: :create


  def add_line_items_from_cart(cart)
    cart.line_items.find_each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

2014/fakefarm/silo/minitest/reference/minishop/app/models/order/confirmation_email_sender.rb
class Order < ActiveRecord::Base
  class ConfirmationEmailSender
    def after_commit(order)
      Notifier.order_received(order).deliver_now
    end
  end
end

2014/fakefarm/silo/minitest/reference/minishop/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action   :authorize, only: [ :new, :create ]
  before_action        :set_order, only: [:show]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @cart = current_cart
    if @cart.empty?
      redirect_to root_url, alert: "Your cart is empty."
    end
    @order = Order.new
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(current_cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil

        format.html { redirect_to root_path, notice: 'Thank you for your order.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:name, :address, :email, :pay_type)
  end
end

2014/fakefarm/silo/minitest/reference/minishop/app/helpers/orders_helper.rb
module OrdersHelper
end

2014/fakefarm/silo/minitest/reference/minishop/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, rows: 3 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :pay_type %><br>
    <%= f.select :pay_type, Order::PAYMENT_TYPES,
                 prompt: 'Select a payment method' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

2014/fakefarm/silo/minitest/reference/minishop/app/views/orders/index.html.erb
<%= render_message %>

<div id="orders">
  <h1>Orders</h1>
  <table>
    <thead>
      <tr>
	<th>Name</th>
	<th>Address</th>
	<th>Email</th>
	<th>Payment Type</th>
	<th></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
	<tr id="order#{ order.id }" class="order <%= cycle('list_line_odd', 'list_line_even' ) %>" >
          <td><%= order.name %></td>
          <td><%= order.address %></td>
          <td><%= order.email %></td>
          <td><%= order.pay_type %></td>
        <td class="list_actions">
          <%= link_to 'Show', order %><br/>
	</td>
      </tr>
    <% end %>
  </table>
</div>

2014/fakefarm/silo/minitest/reference/minishop/app/views/orders/new.html.erb
<div id="order" class="order new">
  <h1>Complete your order:</h1>

  <%= render_message %>

  <%= render 'form' %>
</div>

2014/fakefarm/silo/minitest/reference/minishop/app/views/orders/show.html.erb
<h1>Order <%= @order.id %></h1>

<%= render_message %>

<div id="order_#{ @order.id }" class="order show">
  <p>
    <strong>Name:</strong>
    <span><%= @order.name %></span>
  </p>

  <p>
    <strong>Address:</strong>
    <span><%= @order.address %></span>
  </p>

  <p>
    <strong>Email:</strong>
    <span><%= @order.email %></span>
  </p>

  <p>
    <strong>Payment Type:</strong>
    <span><%= @order.pay_type %></span>
  </p>
</div>

<%= link_to 'Back', orders_path %>